//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WireNote.rc
//
#define ID_ENTCODE                      2
#define IDOK2                           2
#define IDACTIONS                       3
#define IDRESET                         3
#define ID_WEBSITE                      3
#define IDMINIMIZE                      3
#define IDFIND                          3
#define IDDELETE                        4
#define ID_FOLDERACTIONS1               4
#define ID_FOLDERACTIONS2               5
#define ID_CYCLEBG                      6
#define ID_FOLDERSEL                    8
#define IDAPPLY                         10
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WPOSSORGANIZATOR_DIALOG     102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_PROPSHT_CAPTION             104
#define IDS_PROPSHT_CAPTION1            108
#define IDD_WPHTMLVIEW                  112
#define IDB_BM_ORGAICON                 127
#define IDR_MAINICO                     128
#define IDR_SYSTRAY                     129
#define IDD_NEWTASK                     130
#define IDD_NEWREMINDER                 130
#define IDD_REPORTFROM                  131
#define IDD_NOTE                        132
#define IDD_NOTESETTINGS                134
#define IDD_PERSON                      145
#define IDD_ADDRESSBOOK                 146
#define IDR_NOTE_MENU                   150
#define IDI_FOURICONS                   153
#define IDD_DLGSTYLES                   154
#define IDI_ADDTOADDRB                  156
#define IDD_REMINDER                    156
#define IDI_PINNEDUP                    161
#define IDI_PINNEDDOWN                  162
#define IDI_PINNEDUP_APP                163
#define IDI_ADDRBOOK                    164
#define IDB_BM_NEWTODO                  166
#define IDB_BM_ADRBOOK                  167
#define IDB_BM_NEWPERSON                168
#define IDB_BM_NEWREMAINDER             169
#define IDR_TODOMENU                    169
#define IDB_BM_DEL                      170
#define IDB_BM_TODODONE                 171
#define IDB_BM_TODOINFO                 172
#define IDB_BM_TODOMOD                  173
#define IDB_BM_NEWMESSAGE               175
#define IDB_PINNED_UP                   177
#define IDB_BM_TODOCURRENT              180
#define IDB_BM_TEMP5                    181
#define IDB_BM_NEWNOTE                  182
#define IDD_INFO_WND                    182
#define IDB_BM_TEMP2                    183
#define IDI_ICON_INFO_AST               183
#define IDB_BM_DELPERSON                184
#define IDI_ICON_INFO_REMINDER          184
#define IDB_BM_MODPERSON                185
#define IDI_ICON_INFO_MES               185
#define IDB_PINNED_UP_APP               186
#define IDB_PINNED_DOWN                 187
#define IDB_IMAGELIST                   188
#define IDR_REMINDERMENU                189
#define IDB_BM_ACTREMAINDER             189
#define IDR_FOLDERMENU                  190
#define IDB_BM_SAVE                     190
#define IDR_PRIORITYMENU                191
#define IDB_BM_OPTIONS                  191
#define IDR_INFOWND_MENU                192
#define IDB_BM_MSGLOG                   192
#define IDD_WCHANGER                    193
#define IDR_WCHANGER                    194
#define IDI_ICON_INFO_MES_OK            195
#define IDI_ICON_INFO_MES_ERROR         196
#define IDR_MENU_ADDRBOOK               197
#define IDI_ADDRBOOK_AWAY               199
#define IDI_ADDRBOOK_BUSY               200
#define IDI_ADDRBOOK_DND                201
#define IDB_BM_PONLINE                  202
#define IDB_BM_PAWAY                    203
#define IDB_BM_PBUSY                    204
#define IDB_BM_PDND                     205
#define IDB_BM_POFFLINE                 206
#define IDB_BM_PGROUP                   207
#define IDB_BM_PUNKNOWN                 208
#define IDB_BM_REFRESH                  209
#define IDR_FILELINKMENU                211
#define IDI_ADDRBOOK_NEWMSG1            221
#define IDI_ADDRBOOK_NEWMSG2            222
#define IDI_ADDRBOOK_NEWMSG3            223
#define IDI_ADDRBOOK_NEWMSG4            224
#define IDB_REMDACTIONS                 230
#define IDB_BM_MESCNTR                  233
#define IDB_BM_WCH                      234
#define IDB_BM_INMESSAGE                235
#define IDI_ICON_MAIN2                  241
#define IDI_ICON_MAIN3                  242
#define IDI_ICON_MAIN4                  243
#define IDI_ICON_MAIN5                  244
#define IDI_ICON_MAIN6                  245
#define IDI_ICON_MAIN7                  246
#define IDD_PROTDIALOG                  248
#define ID_W_ADDDIRECTORY               249
#define IDD_WPLINK                      250
#define IDI_CHWALLPICON                 251
#define IDB_BM_INMESSAGE_F1             254
#define IDB_BM_INMESSAGE_F2             255
#define IDB_BM_INMESSAGE_F3             256
#define IDB_BM_INMESSAGE_F4             257
#define IDB_BM_INMESSAGE_F5             258
#define IDB_BM_INMESSAGE_F6             259
#define IDD_OPTIONS_DIALOG              260
#define ID_NOTEMENU_NEWSTYLE            262
#define IDD_SIMPLECHOOSER               263
#define IDB_BITMAP_CLOCK                264
#define ID_FOLDER_RENAMEFOLDER          265
#define IDB_BM_DELNOTE                  266
#define IDB_BM_NOTESIZE                 267
#define IDB_BM_NOTEREPL                 269
#define IDB_BM_LOGO                     270
#define IDB_BM_HELP                     271
#define ID_NOTEMENU_NEWFNT              272
#define IDI_ICON_NOTE                   273
#define IDI_ICON_ASK                    274
#define IDB_BM_LICKEY                   275
#define IDB_BM_CHANGECOL                277
#define IDI_ICON_BG                     278
#define IDI_ICON_MINIM                  279
#define ID_SYSTRAY_OPENWIREKEYS         280
#define IDI_ICON_WIREKEYS               281
#define IDB_BM_NEW                      282
#define IDB_BM_MSG_OK                   287
#define IDB_BM_MSG_ERR                  288
#define IDB_BM_MSG_IN                   289
#define IDB_BM_ABPROG                   290
#define IDB_BM_MSG_SEND                 291
#define IDB_BM_SKREPKA                  292
#define IDB_BM_PRINT                    293
#define IDB_BM_FIND                     294
#define IDD_FIND                        295
#define IDB_BM_NOTECOPY                 295
#define IDD_ANTISPAM                    296
#define IDI_ICON_MAIL                   297
#define IDD_SIMPLEEDIT                  298
#define IDR_SPAMMSG_MENU                299
#define IDB_BM_RECENT                   300
#define IDI_UPNOTIFY                    301
#define IDB_BM_NEWPERSON_COPY           302
#define IDC_CURSOR_DRAG                 303
#define IDB_BM_EDIT                     304
#define IDB_BM_NFOLDER                  305
#define IDB_BM_NLINK                    306
#define IDB_BM_NEWTAB                   307
#define IDB_BM_DELTAB                   308
#define IDB_BM_EDITAB                   309
#define IDB_BM_POPTAB                   310
#define IDB_BM_NEWMESSAGE2              311
#define IDB_BM_SHARE                    312
#define IDB_BM_EFORM                    313
#define IDB_BM_EFORM1                   314
#define IDB_BM_NEWNOTE2                 315
#define IDB_BM_NEWMESSAGESM             316
#define IDMINIMAZE                      1000
#define IDC_STATIC2                     1001
#define IDC_EDIT_NTNAME                 1002
#define ID_REPORT                       1002
#define IDC_EDIT_NTDSC                  1003
#define IDC_TASKLIST                    1003
#define IDC_SHOW_TASK                   1004
#define IDC_TASK_INFO                   1005
#define IDC_DELETE_TASK                 1006
#define IDC_MONTHCALENDAR               1007
#define IDC_DELETE_TASK_HIDE            1007
#define IDC_TASK_MOD                    1008
#define IDC_TEXTFIELD                   1009
#define IDC_TASK_UNDONE                 1009
#define IDC_NOTE_OPTION                 1011
#define IDC_NOTE_REPLY                  1012
#define IDC_NOTE_RED                    1013
#define IDC_NOTE_ONTOP                  1015
#define IDC_NOTE_OPTDIALOG              1016
#define IDC_NOTE_DEL                    1017
#define IDC_NOTEOPT_FRAME               1018
#define IDC_NOTE_COPYTOCL               1019
#define IDC_NOTE_OPTMENU                1020
#define IDC_NOTE_ICON                   1021
#define IDC_NOTE_SAFETOFILE             1022
#define IDC_NOTE_FIXSIZE                1023
#define IDC_NOTE_HISTORY                1024
#define IDC_COMBOBOXEX                  1025
#define IDC_SENDTO                      1027
#define IDC_POPUPTIME                   1028
#define IDC_ADDTOADRBOOK                1028
#define IDC_SAVEONEXIT                  1029
#define IDC_SENDMESSAGE                 1029
#define IDC_COLORSCHEME                 1030
#define IDC_ABOOK                       1030
#define IDC_TITLE                       1031
#define IDC_KEEPFOREVER                 1032
#define IDC_RECENTA                     1032
#define IDC_LOG_FILE                    1033
#define IDC_PINUPTITLE                  1033
#define IDC_REP_FILE                    1034
#define IDC_PINUP                       1034
#define IDC_PINUP_STATIC                1034
#define IDC_BUTTON_LOG                  1035
#define IDC_AUTOHIDE                    1035
#define IDC_ADR_FILE                    1036
#define IDC_READONLY                    1036
#define IDC_AUTOPOUPBYDEF               1037
#define IDC_NOTESTYLE                   1038
#define IDC_TASKNOTE_STYLE              1039
#define IDC_NOTESTARTMODE               1039
#define IDC_REMDSTYLE                   1040
#define IDC_CHECK_SAVENOTES             1041
#define IDC_MESSAGENOTE_STYLE           1041
#define IDC_CHECK_EXT                   1042
#define IDC_CHECK_SCROLLBARS            1042
#define IDC_CHECK_CONF_TO_TRAY          1042
#define IDC_CHECK_WORDWRAP              1042
#define IDC_USEWORDWRAP                 1042
#define IDC_ALERT_STYLE                 1042
#define IDC_NOTES_DIR                   1043
#define IDC_CHECK_AUTORUNMESCENTER      1043
#define IDC_CHECK_AUTOQUOTE             1043
#define IDC_MAIN_STYLE                  1043
#define IDC_TASK_DIR                    1044
#define IDC_CHECK_SOUNDONARR            1044
#define IDC_MESSAGENOTE_ONDUPL          1044
#define IDC_BUTTON_TASKS                1045
#define IDC_CHECK_AUTOSHOW_MSG          1045
#define IDC_CHECK_SOUNDONREM            1045
#define IDC_CHECK_AUTOAWAY              1045
#define IDC_BUTTON_ADDR                 1046
#define IDC_CHECK_AR_FORUNK             1046
#define IDC_CHECK_MSG_DELIV             1046
#define IDC_BUTTON_ADDSTR               1046
#define IDC_BUTTON_REP                  1047
#define IDC_ONLINE_STATUS               1047
#define IDC_CHECK_MSG_NOTDELIV          1047
#define IDC_BUTTON_EDITSTR              1047
#define IDC_BUTTON_NOTES                1048
#define IDC_CHECK_MSG_SEND              1048
#define IDC_CHECK_HIDEMSGFLD            1048
#define IDC_MENUITEMSCOUNT              1049
#define IDC_BUTTON_SETBGCOL             1049
#define IDC_CHECK_AUTODEL_MSG           1049
#define IDC_CHECK_TODOACITIZATION       1049
#define IDC_TASKDAYS                    1050
#define IDC_MENUSTICK                   1050
#define IDC_BUTTON_SETFONT              1050
#define IDC_CHECK_WWMSG                 1050
#define IDC_CHECK_TODODONE              1050
#define IDC_EDIT_IP                     1051
#define IDC_NOTESDAYS                   1051
#define IDC_INCLUDEINREP                1051
#define IDC_MENU_AUTOSAVETIME           1051
#define IDC_CHECK_AUTODELALERT          1051
#define IDC_CHECK_ERROR                 1051
#define IDC_EDIT_NICK                   1052
#define IDC_MESSAGENOTE_ONNEW           1052
#define IDC_CHECK_COPYCLIP              1052
#define IDC_NEWPERSON                   1053
#define IDC_EDIT_DSC                    1053
#define IDC_CHECK_PASTECLIP             1053
#define IDC_CHECK_USENICKS              1053
#define ID_DELETEPERSON                 1054
#define IDC_CHECK_USEFILTERS            1054
#define ID_MSGLOG                       1055
#define IDC_CHECK_HIDEMSGFLD2           1055
#define IDC_CHECK_AUTOPOPUPAB           1055
#define IDC_PERSONLIST                  1056
#define IDC_MODPERSON                   1057
#define IDC_CHECK_STARUP_WITHWIN        1057
#define IDC_PERSONMOVEDOWN              1058
#define IDC_STATIC1                     1058
#define IDC_CHECK_STARUP_ADDCLIP        1058
#define IDC_SENDMES                     1058
#define IDC_PERSONMOVEUP                1059
#define IDC_STATIC3                     1059
#define IDC_CHECK_CTRL                  1059
#define ID_REFRESHSTAT                  1059
#define IDC_BUTTON_ADD                  1060
#define IDC_CHECK_SHIFT                 1060
#define ID_QMENU                        1060
#define IDC_BUTTON_DEL                  1061
#define IDC_CHECK_ALT                   1061
#define ID_ADOPTIONS                    1061
#define IDC_CUR_STYLE                   1062
#define IDC_CHECK_USEDBLCLICK           1062
#define IDC_FINDPERSON                  1062
#define IDC_BUTTON_RND                  1063
#define IDC_CHECK_SYSACTIONS            1063
#define IDC_TAB_NEW                     1063
#define IDC_SENDMES2                    1063
#define IDC_BUTTON_SETTXTCOL            1064
#define IDC_CHECK_SHOWTOOLTIP           1064
#define IDC_TAB_DEL                     1064
#define IDC_BUTTON_REN                  1065
#define IDC_TAB_REN                     1065
#define IDC_STATIC_TXT                  1067
#define IDC_STATIC_BG                   1068
#define IDC_STATIC_FONT                 1069
#define IDC_REMINDER_FILE               1069
#define IDC_BUTTON_REMFILE              1070
#define IDC_CURSTYLE                    1070
#define IDC_CURSORSAVE                  1070
#define IDC_BUTTON_REMFILE_PLAY         1071
#define IDC_CHECK_AUTOPOPUPMAINWND      1072
#define IDC_CHECK_SHOWDONE              1073
#define IDC_CHECK_SHOWINLIST            1074
#define IDC_CHECK_HOURTICKER            1075
#define IDC_CHECK_SHOWINLIST_NOTE       1076
#define IDC_CHECK_DRAWFRAME             1077
#define IDC_CHECK_SHOWINLIST_REMD       1078
#define IDC_CHECK_ACTIVENEWTD           1079
#define IDC_CHECK_MOVETOMSG             1080
#define IDC_DSC                         1081
#define IDC_CHECK_USEANIM               1081
#define IDC_CHECK_HIDEPINUPED           1081
#define IDC_LATER                       1082
#define IDC_CHECK_LOGTODOHIST           1082
#define IDC_REPITING                    1083
#define IDC_CHECK_AUTOACTIV             1083
#define IDC_COMBO2                      1084
#define IDC_COMBO_WDAYS                 1084
#define IDC_CHECK_DONEACTIVATETOO       1084
#define IDC_DATE_PICK                   1085
#define IDC_COMBO_MONLIST               1085
#define IDC_TIME_PICK                   1086
#define IDC_CHECK1                      1087
#define IDC_TAGFINDER                   1087
#define IDC_ACTIVE                      1087
#define IDC_PREVIEW_CHECK               1087
#define IDC_CHECK_GROUP                 1087
#define IDC_ASKAGAIN                    1087
#define IDC_CHECK_RUNEMAILC             1087
#define IDC_ACTION                      1088
#define IDC_ACTION_DEF                  1089
#define IDC_BIGBUTTONS                  1090
#define IDC_FRAME                       1091
#define IDC_BACKDELS                    1091
#define IDC_AUTOPINUPINTENDO            1092
#define IDC_STATIC_TITLE                1093
#define IDC_CHECK_USE                   1095
#define IDC_COMBO_ACTION                1096
#define IDC_EDIT_ACTION_PAR             1097
#define IDC_BUTTON_SAVEEXIT             1098
#define IDC_BUTTON_DONTSAVEEXIT         1099
#define IDC_BUTTON_DELETE               1100
#define IDC_BUTTON_CVIEW                1101
#define IDC_RADIO_DAY_EXACT             1102
#define IDC_RADIO_DAY_EVERY             1103
#define IDC_RADIO_DAY_EVERY_WDAY        1104
#define IDC_EDIT_DAY                    1105
#define IDC_RADIO_MON_EXACT             1106
#define IDC_RADIO_MON_EVERY             1107
#define IDC_RADIO_MON_EVERY_MONLIST     1108
#define IDC_EDIT_ACTION_PAR2            1108
#define IDC_EDIT_MONTH                  1109
#define IDC_BUTTON_TEST                 1110
#define IDC_BUTTON_A15                  1111
#define IDC_BUTTON_A60                  1112
#define IDC_TIME                        1113
#define IDC_RADIO_YEAR_EXACT            1115
#define IDC_RADIO_YEAR_EVERY            1116
#define IDC_BUTTON_ACTION_PAR_CHOSER    1117
#define IDC_EDIT_YEAR                   1118
#define IDC_TIME_EVERY                  1120
#define IDC_COMBO_TIME_DISCR            1121
#define IDC_COMBO_HOUR_LIST             1123
#define IDC_WATCH                       1126
#define IDC_RADIO_AM                    1127
#define IDC_RADIO_PM                    1128
#define IDC_STATIC_DAYF                 1129
#define IDC_STATIC_MONF                 1130
#define IDC_STATIC_YEARF                1131
#define IDC_STATIC_TIMEF                1132
#define IDC_TEXT                        1133
#define IDC_ALPHA_SLIDER                1135
#define IDC_MESSAGE_DIR                 1136
#define IDC_BUTTON_MESLOGFILE           1137
#define IDC_PRIORITY                    1138
#define IDC_MESSAGESOUND_FILE           1138
#define IDC_BUTTON_PROTOCOLS            1138
#define IDC_COMBO_PR                    1139
#define IDC_BUTTON_MESSOUND             1139
#define IDC_BUTTON_FILTERS              1139
#define IDC_COMBO_TRAYMENU              1140
#define IDC_MESUPDATETIME               1140
#define IDC_CHECK_MSG_DELIV_E           1140
#define IDC_LIST_WPAPERS                1141
#define IDC_COMBO_TRAYMENU_MC           1141
#define IDC_BUTTON_MSGDELIV             1141
#define IDC_CHECK_ANIMTYPE              1141
#define IDC_ANIMTYPE                    1141
#define IDC_PREVIEW                     1142
#define IDC_CHECK_MSG_NOTDELIV_E        1142
#define IDC_HOUR                        1143
#define IDC_BUTTON_MSGNOTDELIV          1143
#define IDC_MIN                         1144
#define IDC_BUTTON_MESSOUND_PLAY        1144
#define IDC_DVOETOCHIE                  1145
#define IDC_BUTTON_MSGDELIV_CH          1145
#define IDC_BUTTON_MSGNOTDELIV_CH       1146
#define IDC_STATIC_PERIOD               1147
#define IDC_CHECK_MSG_SEND_E            1147
#define IDC_STATIC_NEXTWPT              1147
#define IDC_FILEINFO                    1148
#define IDC_BUTTON_SENDMSG              1148
#define IDC_RESINFO                     1148
#define IDC_RADIO_RND                   1149
#define IDC_BUTTON_SENDMSG_CH           1149
#define IDC_RADIO_CYCLE                 1150
#define IDC_EDIT_TODOACTIVIZATION       1150
#define IDC_CHECK_CHONSTART             1151
#define IDC_BUTTON_TODOACTIV            1151
#define IDC_RESINFO2                    1151
#define IDC_FORSTAT                     1151
#define IDC_CHECK_ACTIVE                1152
#define IDC_BUTTON_TODOACTIVA_TEST      1152
#define IDC_SETNOW                      1153
#define IDC_EDIT_TODODONE               1153
#define IDC_CHECK_SHOWINACTIVE          1154
#define IDC_CHECK_SHOWINACTIVE_REMD     1154
#define IDC_BUTTON_TODODONE             1154
#define IDC_CHECK_IFSCRSAVER            1154
#define IDC_ADVANCED                    1154
#define IDC_EDIT_WEIGHT                 1155
#define IDC_BUTTON_TODODONE_TEST        1155
#define IDC_CHECK_CHTRAYICON            1155
#define IDC_STATIC_WEIGHT               1156
#define IDC_CHECK_ERRWAV                1156
#define IDC_CHECK_HTML                  1156
#define IDC_STATIC_QUAL                 1157
#define IDC_BUTTON_ERR                  1157
#define IDC_BUTTON_MSGNOTDELIV_CH2      1158
#define IDC_BUTTON_ERRCHK               1158
#define IDC_STATIC_FG                   1158
#define IDC_NEW_TODO                    1159
#define IDC_CHECK_COPYWAV               1159
#define IDC_NEW_NOTE                    1160
#define IDC_BUTTON_COPYFILE             1160
#define IDC_NEW_REMINDER                1161
#define IDC_EDIT_AUTOREPS               1161
#define IDC_BUTTON_COPYSOUND            1161
#define IDC_NEW_MESSAGE                 1162
#define IDC_CHECK_PASTEWAV              1162
#define IDC_ADDRBOOK                    1163
#define IDC_BUTTON_PASTEFILE            1163
#define IDC_OPTIONS_BT                  1164
#define IDC_BUTTON_ERRCHK3              1164
#define IDC_BUTTON_PASTEPLAY            1164
#define IDC_SAVEALL_BT                  1165
#define IDC_TOOLBAR                     1166
#define IDC_WNDONTOP                    1166
#define IDC_LIST1                       1167
#define IDC_FIND_BT                     1167
#define IDC_NEW_LINK                    1168
#define IDC_EDIT_ITEM                   1169
#define IDC_COMBO_ICON                  1170
#define IDC_DELETE_ITEM                 1170
#define IDC_NEW_FOLDER2                 1171
#define IDC_EDITFORM                    1172
#define IDC_HOTKEY1                     1173
#define IDC_STATIC_THEME                1174
#define IDC_STATIC_THEME_NAME           1175
#define IDC_COMBO_THEMEFITTING          1176
#define IDC_COMBO_QUALITY               1177
#define IDC_SLIDER_ICON                 1177
#define IDC_COMBO_QUALITY2              1178
#define IDC_COMBO_FOREGROUND            1178
#define IDC_BUTTON_ICON                 1179
#define IDC_CHECK_PROT1                 1180
#define IDC_CHECK_PROT2                 1181
#define IDC_CHECK_PROT3                 1182
#define IDC_RADIO_PROT1                 1183
#define IDC_XPC_PORT                    1184
#define IDC_RADIO_PROT2                 1185
#define IDC_RADIO_PROT3                 1186
#define IDC_ADD                         1186
#define IDC_XPC_PORT2                   1187
#define IDC_NB_ALIAS                    1187
#define IDC_HISTRORYTRACKING            1187
#define IDC_XPC_PORT3                   1188
#define IDC_ML_SLOT                     1188
#define IDC_EDIT1                       1188
#define IDC_TIMEOUT                     1188
#define IDC_MASK                        1188
#define IDC_EDIT_TITLE                  1188
#define IDC_EDIT_FIND                   1188
#define ID_BROWSE                       1189
#define IDC_BUTTON1                     1189
#define IDC_NETTIMEOUT                  1189
#define IDC_OK                          1189
#define IDC_LOGO                        1189
#define IDC_WICON                       1189
#define IDC_COMPADDR                    1189
#define IDC_GO                          1189
#define IDC_EDIT_SPAMSTR                1189
#define IDC_BUTTON_FIND                 1189
#define IDC_OPTIONSLIST                 1190
#define IDC_STATIC_NTIT                 1191
#define IDC_LPANE                       1191
#define IDC_STATIC_COLSCH               1192
#define IDC_STATIC_DSC                  1194
#define IDC_STATIC_BGCOL                1195
#define IDC_STATIC_CURSTYLE             1196
#define IDC_STATIC_TEXTCOL              1197
#define IDC_STATIC_TSTFONT              1198
#define IDC_STATIC_ALPHA                1199
#define IDC_STATIC_MAINS                1200
#define IDC_STATIC_REMS                 1201
#define IDC_STATIC_NOTES                1202
#define IDC_STATIC_TNOTES               1203
#define IDC_STATIC_MSGS                 1204
#define IDC_STATIC_ALERTS               1205
#define IDC_STATIC_FRAME                1207
#define IDC_COMBO                       1208
#define IDC_PRTITLE                     1209
#define IDC_REGSTATUS                   1210
#define IDC_PRVERSION                   1211
#define IDC_LEGALNOTICE                 1212
#define IDC_QHELP_TXT                   1213
#define IDC_COPYRIGHT                   1213
#define ID_FOLDER                       1213
#define IDC_DOWNLOADDSC                 1214
#define ID_FOLDERTITLE                  1214
#define IDC_RESULTS                     1214
#define IDC_QHELP                       1215
#define IDC_EMDSC                       1215
#define IDC_NOTES                       1215
#define IDC_TODOS                       1216
#define IDC_DSC_TEXT                    1217
#define IDC_TITLES                      1218
#define IDC_STATUS                      1219
#define IDC_DSC_IN                      1221
#define IDC_COMBO_PROT                  1222
#define IDC_SPAMMSG                     1223
#define IDC_COMBO_TAB                   1223
#define IDC_CURRENTSTEP                 1224
#define IDC_CLOSE                       1229
#define IDC_REFILTER                    1230
#define IDC_BUTTON_MULTY                1231
#define IDC_SELALL                      1232
#define IDC_SELNOTHING                  1233
#define IDC_CONFIG                      1234
#define IDC_SERVERLOG                   1235
#define IDC_RUNEMAILCLIENT              1236
#define IDC_ADDTOSPAM                   1237
#define IDC_SPAMTYPE                    1238
#define IDC_VIEWLOG                     1239
#define IDC_AUTODISTRAN                 1239
#define IDC_EDIT                        1239
#define IDC_STATS                       1240
#define IDC_SPAMTYPE2                   1240
#define IDC_INFO                        1241
#define IDC_TAB                         1243
#define IDC_RICHEDIT                    1244
#define IDC_SLIDER_TRANS                1245
#define IDC_NOTE_PRINTBT                1246
#define IDC_SLIDER_VERT                 1246
#define IDC_SLIDER_HORZ                 1247
#define ID_SYSTRAY_OPEN                 32771
#define ID_SYSTRAY_EXIT                 32772
#define ID_SYSTRAY_NEWTASK              32773
#define ID_SYSTRAY_OPTIONS              32774
#define ID_SYSTRAY_NEWNOTE              32775
#define ID_SYSTRAY_SWITCHMENU           32776
#define ID_SYSTRAY_ADDRESSBOOK          32777
#define ID_SYSTRAY_SHOWALLNOTES         32778
#define ID_SYSTRAY_DEFACTION            32779
#define ID_SYSTRAY_NEWREMINDER          32780
#define ID_SYSTRAY_SWITCHTOTASKS        32781
#define ID_SYSTRAY_SWITCHTONOTES        32782
#define ID_SYSTRAY_SWITCHTOREMINDERS    32783
#define ID_SYSTRAY_FIRSTITEM            32784
#define ID_NOTEMENU_HIDENOTE            32785
#define ID_NOTEMENU_SAVENOTES           32786
#define ID_NOTEMENU_SMALLVIEW           32787
#define ID_NOTEMENU_BUTTONVIEW          32788
#define ID_NOTEMENU_EXTENDEDVIEW        32789
#define ID_SYSTRAY_NEWMESSAGE           32790
#define ID_TODO_VIEWTODONOTE            32791
#define ID_TODO_MARKASDONE              32792
#define ID_TODO_MARKASUNDONE            32793
#define ID_TODO_DELETETODO              32794
#define ID_TODO_MODIFYTODO              32795
#define ID_TODO_NEWTODO                 32796
#define ID_TODO_SETASCURRENT            32797
#define ID_TODO_TODOREPORT              32798
#define ID_NOTEMENU_PREVENTFROMEDIT     32799
#define ID_NOTEMENU_AUTOHIDE            32800
#define ID_NOTEMENU_AUTODISP            32801
#define ID_NOTEMENU_REMINDIN1H          32802
#define ID_NOTEMENU_REMINDTOMORROW      32803
#define ID_NOTEMENU_REMINDIN30MIN       32804
#define ID_NOTEMENU_REMINDIN15MIN       32805
#define ID_NOTEMENU_REMINDAFTER3H       32806
#define ID_NOTEMENU_BRINGALLONTOP       32807
#define ID_NOTEMENU_SNAPTOCONTENT       32808
#define ID_REMINDERMENU_ACTIVATEREMINDER 32809
#define ID_REMINDERMENU_DEACTIVATEREMINDER 32810
#define ID_REMINDERMENU_DELETEREMINDER  32811
#define ID_REMINDERMENU_MODIFYREMINDER  32812
#define ID_FOLDER_DELETE                32813
#define ID_FOLDER_CREATENEW             32814
#define ID_NOTEMENU_SHOWNOTE            32816
#define ID_PRIORITY_LOWEREST            32817
#define ID_PRIORITY_LOW                 32818
#define ID_PRIORITY_NORMAL              32819
#define ID_PRIORITY_HIGH                32820
#define ID_PRIORITY_HIGHEST             32821
#define ID_NOTEMENU_WORDWRAP            32822
#define ID_INFOWND_OPEN                 32823
#define ID_INFOWND_DELETE               32824
#define ID_SYSTRAY_WCHANGER             32825
#define ID_WCHANGER_ADDFILE             32826
#define ID_WCHANGER_DELETEALL           32828
#define ID_WCHANGER_DELETEFOLDER        32829
#define ID_WCHANGER_NEWFOLDER           32830
#define ID_ADDFULLFOLDER                32833
#define ID_SYSTRAY_CHANGEWALLPAPER      32834
#define ID_TRAY_OPENWINDOW              32835
#define ID_TRAY_EXITWINDOW              32836
#define ID_FOLDER_ADDTASK               32837
#define ID_FOLDER_ADDNOTE               32838
#define ID_FOLDER_ADDREMINDER           32839
#define ID_TRAY_AUTOANSWERING           32840
#define ID_TRAY_STATUSONLINE            32841
#define ID_TRAY_STATUSBUSY              32842
#define ID_TRAY_STATUSDND               32843
#define ID_TRAY_STATUSAWAY              32844
#define ID_TRAY_NEWMESSAGE              32845
#define IDR_FILELINKMENU_DEL            32846
#define IDR_FILELINKMENU_ACTIVATE       32847
#define ID_FILELINKMENU_RENAME          32848
#define ID_BUTTON32849                  32849
#define ID_BUTTON32850                  32850
#define ID_TRAY_RECONNECT               32851
#define ID_TRAY_REFRESHSTATUS           32852
#define ID_TODO_HIDESHOWDONE            32854
#define ID_REMINDERMENU_SHOWHIDEINACTIVE 32855
#define ID_TODO_SETASNOTCURRENT         32856
#define ID_NOTEMENU_ICONVIEW            32857
#define ID_NOTEMENU_PINNOTE             32858
#define ID_NOTEMENU_BACKNORMALVIEW      32859
#define ID_NOTEMENU_PINTOUNDERLAINGWINDOW 32860
#define ID_NOTEMENU_FIXEDSIZE           32861
#define ID_NOTEMENU_UNPINNOTE           32862
#define ID_HOTMENU_BRINGINVIEW          32862
#define ID_HOTMENU_SEMITRANSPARENT      32863
#define ID_HOTMENU_COPYTOCLIPBOARD1     32864
#define ID_HOTMENU_COPYTOCLIPBOARD2     32865
#define ID_HOTMENU_COPYTOCLIPBOARD3     32866
#define ID_HOTMENU_COPYTOCLIPBOARD4     32867
#define ID_HOTMENU_COPYTOCLIPBOARD5     32868
#define ID_HOTMENU_EXITMENU             32869
#define ID_HOTMENU_PASTEFROMCLIPBOARD1  32870
#define ID_HOTMENU_PASTEFROMCLIPBOARD2  32871
#define ID_HOTMENU_PASTEFROMCLIPBOARD3  32872
#define ID_HOTMENU_PASTEFROMCLIPBOARD4  32873
#define ID_HOTMENU_PASTEFROMCLIPBOARD5  32874
#define ID_HOTMENU_KILLPROCESS          32875
#define ID_HOTMENU_TRANSPARENCY100      32876
#define ID_HOTMENU_TRANSPARENCY80       32877
#define ID_HOTMENU_TRANSPARENCY60       32878
#define ID_HOTMENU_TRANSPARENCY40       32879
#define ID_HOTMENU_TRANSPARENCY20       32880
#define ID_HOTMENU_SWITCHONTOP          32881
#define ID_HOTMENU_POPUPMAINWINDOW      32882
#define ID_REMINDERMENU_ADD             32883
#define ID_FOLDER_SETASTRAYFOLDER       32884
#define ID_TRAY_NEWPERSON               32885
#define ID_TRAY_MODPERSON               32886
#define ID_TRAY_DELPERSON               32887
#define ID_TRAY_NEWMESSAGEONPERSON      32888
#define ID_TRAY_MESSAGELOG              32889
#define ID_HOTMENU_OPENEDFILEHANDLES    32890
#define ID_HOTMENU_ALLOPENEDHANDLES     32891
#define ID_FILELINKMENU_SHOWLOCK        32892
#define ID_HOTMENU_HIDETOTRAY           32893
#define ID_HOTMENU_KILLPROC             32894
#define ID_WCHANGER_ADDHYPERLINK        32895
#define ID_HOTMENU_FREEMEMORY           32896
#define ID_HOTMENU_CONVERTSELECTED      32897
#define ID_TRAY_UPDATEPERSONSTATUS      32898
#define ID_TRAY_OPENCOMPUTER            32899
#define ID_NOTEMENU_SMILEY2             32900
#define ID_NOTEMENU_SMILEY1             32902
#define ID_NOTEMENU_SMILEY4             32903
#define ID_NOTEMENU_SMILEY5             32905
#define ID_NOTEMENU_SMILEY3             32906
#define ID_NOTEMENU_SMILEY6             32907
#define ID_HOTMENU_UPPERCASE            32908
#define ID_HOTMENU_LOWERCASE            32909
#define ID_HOTMENU_COUNTCHARACTERS      32910
#define ID_NOTEMENU_SMILEYOFF           32911
#define ID_NOTEMENU_ATTACHFILE          32912
#define ID_TRAY_USERMSGLOG              32913
#define ID_NOTEMENU_MSGLOG              32914
#define ID_SYSTRAY_ABOUT                32915
#define ID_SYSTRAY_HELP                 32916
#define ID_SYSTRAY_REGISTER             32917
#define ID_TRAY_OPTIONS                 32918
#define ID_NOTEMENU_COPY                32919
#define ID_NOTEMENU_PASTE               32920
#define ID_NOTEMENU_CUT                 32921
#define ID_TODO_REMINDABOUT             32922
#define ID_NOTEMENU_SAVETOFILE          32923
#define ID_NOTEMENU_LOADFROMFILE        32924
#define ID_SYSTRAY_SENDASUGGESTION      32928
#define ID_NOTEMENU_PRINT               32930
#define ID_NOTEMENU_SENDASEMAIL         32931
#define ID_TODO_ADDOPTIONS              32932
#define ID_FILELINKMENU_COPYTOCLIPBOARD 32933
#define ID_SYSTRAY_AUTOPOPUPORGANIZER   32934
#define ID_NOTEMENU_NOTEOPTIONS         32935
#define ID_NOTEMENU_NETWORKSETTINGS     32936
#define ID_NOTEMENU_MESSAGEOPTIONS      32937
#define ID_NOTEMENU_MESSAGEFILTER       32938
#define ID_TODO_TODOSETTINGS            32938
#define ID_ITEM_SENDASMESSAGE           32939
#define ID_SYSTRAY_REFRESHSHAREDREMINDERS 32940
#define ID_SYSTRAY_REMINDERSETTINGS     32941
#define ID_SYSTRAY_ANTISPAMOPTIONS      32942
#define ID_NOTEMENU_OPENADDRESSBOOK     32943
#define ID_SYSTRAY_CHECKFORUPDATES      32944
#define ID_FILELINKMENU_EDITLINK        32945
#define ID_RCLICK_REREAD                32946
#define ID_RCLICK_DELETEFROMSERVER      32947
#define ID_RCLICK_TOGGLEMARK            32948
#define ID_RCLICK_DOWNLOADNEXTLINES     32949
#define ID_RCLICK_SHOWRAWBODY           32950
#define ID_RCLICK_SHOWBODY              32951
#define ID_RCLICK_SHOWALLHEADERS        32952
#define ID_RCLICK_DOWNLOAD20LINESOFBODY 32953
#define ID_RCLICK_DOWNLOAD30LINESOFBODY 32954
#define ID_RCLICK_DOWNLOAD40LINESOFBODY 32955
#define ID_RCLICK_DOWNLOAD50LINESOFBODY 32956
#define ID_NOTEMENU_REMOVEALLATTACHMENTS 32957
#define ID_SYSTRAY_DONATE               32958
#define ID_TRAY_FINDONLINEUSERS         32959
#define ID_NOTEMENU_SWITCHTRANSPARENCY  32960
#define ID_NOTEMENU_REALLYDELETE        32961
#define ID_SYSTRAY_NEWLINK              32962
#define ID_SYSTRAY_LINKFROMCLIPBOARD    32963
#define ID_NOTEMENU_CLIPSPY             32964
#define ID_SYSTRAY_HIDEALLNOTES         32965
#define ID_TRAY_IMPORTAB                32966
#define ID_TRAY_EXPORTAB                32967
#define ID_SYSTRAY_CHECKINCOMINGEMAILS  32968
#define ID_NOTEMENU_ASSIGNHOTKEY        32969
#define ID_SYSTRAY_REPORTALLITEMS       32969
#define ID_SYSTRAY_CBILLB               32970
#define ID_ITEM_SHARE                   32971
#define ID_FZFOLDER                     32972
#define ID_SYSTRAY_SHOWNEXT             32973
#define ID_TODO_SAVETOFILE              32974
#define ID_NOTEMENU_PINMENU             32975
#define ID_SYSTRAY_AUTOPOPUPAB          32976
#define ID_NOTEMENU_SEARCH              32977
#define ID_SYSTRAY_LINKCH               32978
#define ID_NOTEMENU_EXEASSCR            32979
#define ID_NOTEMENU_SNAPTODERF          32980
#define ID_NOTEMENU_POS1                32981
#define ID_NOTEMENU_POS2                32982
#define ID_NOTEMENU_POS3                32983
#define ID_NOTEMENU_ATTACH2WND          32984

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32970
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
