<?php 
function getTitle($l)
{
	global $language;
	return "ScreenCannon - Automated utility for screenshot making";
}
function insertSection($l){
?>
<div id=h1>ScreenCannon</div>

<?php if($l==1){?>
	Эта маленькая и простая программа предназначенна для одной цели - делать скриншот всего что происходит у Вас на экране напрямую в файл, минуя буфер обмена.
	Программа работает во всех играх и при просмотре любого видео. Имя и путь файла для сохранения может создаваться "на лету" из разных параметров - текущего времени, заголовка активного окна или программы с которой Вы работаете
	или играете в данный момент. То есть Вам даже не придется потом сортировать Ваши скриншоты по каталогам - ScreenCannon сделает все за Вас.
	Есть также возможность делать снимок лишь части экрана (выделением прямоугольника мышкой) и автоматическим открытием сделанного скриншота в Вашем любимом 
	редакторе изображений
<?php }else{?>
	This small utility is designed for single task - taking screenshots (capturing screens) from any applications, including games, DVD/Video movies, etc.
	ScreenCannon saves screenshot directly to disk, excluding clipboard. In addition, ScreenCannon can autogenerate screenshot file name and folder based on current time
	or currently running application. You can also take screenshots of rectangular areas of screen (dragging rectangle by mouse)
<?php }?>
<table width=100% border=0 cellpadding=5>
<tr><td>
<?php if($l==1){?>
	<br><br>Возможности:
	<br>- Снятие скриншота всего экрана или его части
	<br>- Работа во всех программах, включая игры и видеопроигрыватели
	<br>- Автосохранение скриншота на диск. Имя файла и каталог могут создаваться "на лету" из различных параметров
	<br>- Добавление надписей к скриншоту (дата/время снятия), сохранение в Jpg формате и многое другое
	<br><br>
	Программа абсолютно бесплатна для некоммерческого использования и не содержит AdWare или SpyWare.
	Для коммерческого использования все же нужно приобрести <a href="http://www.wiredplane.com/guestbook/vendors.php?who=comuse&vendor=2&src=site">лицензию</a>
<?php }else{?>
	<br><br>Features:
	<br>- Taking screenshots of shole screen or any rectangular part
	<br>- Works in all applications including games, DVD/Movie players, etc.
	<br>- Screenshot is automatically saved to disk. File name and folder can be autogenerated from current time, active application, etc.
	<br>- Screenshot can be automatically signed or resized, can be saved in Jpg format
	<br>- And much more, check program to learn all possibilities!
	<br><br>
	This program is totally FREE for non-commersial use and does not contain adware or spyware of any kind.<br>But you can donate us if you find it helpful.
	For commersial usage you should obtain <a href="http://www.wiredplane.com/guestbook/vendors.php?who=comuse&vendor=2&src=site">license</a>
<?php }?>
<td width=10% align=right><img src="/images2/screencannon/screencannon.jpg" border=1 width=140 height=165>
</table>
<br>
<center>
<script type="text/javascript"><!--
google_ad_client = "pub-5186671154037974";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_type = "text_image";
google_ad_channel = "";
google_color_border = "000000";
google_color_bg = "EEEEEE";
google_color_link = "0000FF";
google_color_text = "000000";
google_color_url = "008000";
//-->
</script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</center>
<div width=100% align=center><a href="/download/screencannon.zip"><img src="/images2/button_download.gif" width=148 height=40 vspace=10 hspace=10></a></div>
<br><br>
<?php 
}
include("../cgi-bin/wp_layout.php");
printLayout("common");
?>
