<?php 
	global $languageNumber;
	$l=$languageNumber;
?>
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center" >
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top.gif" width=900 height=32></TD>
</TR>
<TR HEIGHT=100 VALIGN=BOTTOM>
	<TD align=center><a href="../commons/about.php" class=menu><img src="/images2/wirechanger/wirechanger_logo.gif" width=262 height=100></a>
	<a href="/download/wirechanger.zip">Download</a>::<a href="../commons/order.php">Order</a>
	</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_wirechanger.gif" width=100 height=100>
	<a href="../wirechanger/" style="color: #319aff;">WireChanger</a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_wallpapers.gif" width=100 height=100>
	<a href="../wirechanger/wallpapers.php" style="color: #63cf63;"><?php if($l==1){?>Картинки<?php }else{?>Wallpapers<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_widgets.gif" width=100 height=100>
	<a href="../wirechanger/widgets.php" style="color: #ff9a31;"><?php if($l==1){?>Виджеты<?php }else{?>Widgets<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_clocks.gif" width=100 height=100>
	<a href="../wirechanger/wcclocks.php" style="color: #ff6563;"><?php if($l==1){?>Часы<?php }else{?>Clocks<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_noteskin.gif" width=100 height=100>
	<a href="../wirechanger/wcskins.php" style="color: #ce65ce;"><?php if($l==1){?>Скины<?php }else{?>Note skins<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirechanger/hmenu_help.gif" width=100 height=100>
	<a href="../wirechanger-help/contents.shtml" style="color: #9c9a9c;"><?php if($l==1){?>Помощь<?php }else{?>Help<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD><img src="/images2/hmenu_space.gif" width=38 height=100></TD>
</TR>
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top3.gif" width=900 height=32></TD>
</TR>
</TABLE>