<?php 
	global $languageNumber;
	$l=$languageNumber;
?>
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center" >
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top.gif" width=900 height=32></TD>
</TR>
<TR HEIGHT=100 VALIGN=BOTTOM>
	<TD align=center><a href="../commons/about.php" class=menu><img src="/images2/wirekeys/wirekeys_logo.gif" width=262 height=100></a>
	<a href="/download/wirekeys.zip">Download</a>::<a href="../commons/order.php">Order</a>
	</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_wirekeys.gif" width=100 height=100>
	<a href="../wirekeys/" style="color: #319aff;">WireKeys</a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_plugin.gif" width=100 height=100>
	<a href="../wirekeys/wkplugins.php" style="color: #63cf63;"><?php if($l==1){?>Плагины<?php }else{?>Plugins<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_macros.gif" width=100 height=100>
	<a href="../wirekeys/wkmacros.php" style="color: #ff9a31;"><?php if($l==1){?>Макросы<?php }else{?>Macros<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_sources.gif" width=100 height=100>
	<a href="../wirekeys/wksources.php" style="color: #ff6563;"><?php if($l==1){?>Примеры<?php }else{?>Sources<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_tips.gif" width=100 height=100>
	<a href="../wirekeys/tips.php" style="color: #ce65ce;"><?php if($l==1){?>Советы<?php }else{?>Tips&Tricks<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/wirekeys/hmenu_help.gif" width=100 height=100>
	<a href="../wirekeys-help/contents.shtml" style="color: #9c9a9c;"><?php if($l==1){?>Помощь<?php }else{?>Help<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD><img src="/images2/hmenu_space.gif" width=38 height=100></TD>
</TR>
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top3.gif" width=900 height=32></TD>
</TR>
</TABLE>