call createOne.cmd DesktopClocks2 2
call createOne.cmd DesktopClocks3 3
call createOne.cmd DesktopClocks4 4
call createOne.cmd DesktopClocks5 5
call createOne.cmd DesktopClocks6 6
call createOne.cmd DesktopClocks7 7
call createOne.cmd DesktopClocks8 8
call createOne.cmd DesktopClocks9 9
call createOne.cmd DesktopClocks10 10
call createOne.cmd DesktopClocks11 11
call createOne.cmd DesktopClocks12 12
call createOne.cmd DesktopClocks13 13
call createOne.cmd DesktopClocks14 14
call createOne.cmd DesktopClocks15 15
call createOne.cmd DesktopClocks16 16
call createOne.cmd DesktopClocks17 17
call createOne.cmd DesktopClocks18 18
