extern AppMainApp theApp;
extern CSettings objSettings;
extern AppMainDlg* pMainDialogWindow;
extern CCriticalSection csInfoWnds;
extern CStub wk;
extern CCriticalSection csClipAttach;
extern CCriticalSection csClipRecreation;

void GetDesktopInternalName(int iDesk, char szDesktopID[DEF_DESKNAMESIZE]);
DWORD WINAPI PluginOperation(LPVOID pData);
DWORD WINAPI PluginOperation2(LPVOID pData);
DWORD WINAPI PluginOperationX(DWORD wParam,DWORD dwOrigCode);
BOOL UnloadPluginRaw(CPlugin*& oPlug);
BOOL LoadPluginRaw(CPlugin*& oPlug);
void InstallDefaultMacros();
void CheckAndDisablePayFeaturesIfNeeded();
void CheckAndDisablePayFeaturesIfNeeded2();
CString GetClipHistoryName(int iClipNumber);
void SubstMyVariablesForQRun(CString& sParams, CQuickRunItem* pW=NULL, BOOL bJScriptSafe=FALSE, BOOL bNoGetSelection=FALSE, const char* szParAdditions=NULL, const char* szSelectionSubst=NULL);
int PrepareDesktopSwitch(BOOL bPause);
BOOL AddToAutoHide(HWND hWin);
BOOL CreateLinkInFolder(CString sTargetFolder, HWND hWin);
BOOL StartQRunByName(const char* szQRunTitle, const char* szAdditionalParameter, const char* szSelection=0);
void ShowRegNotice(CString sLertText,BOOL bForce=0);
void RandomizeScreensaver();
void MyShutDownComputer(BOOL bRestart, int iType);
BOOL AddSysEventSubmit(int iEventType, FPONSYSTEMEVENT fp);
BOOL RemSysEventSubmit(int iEventType, FPONSYSTEMEVENT fp);
DWORD WINAPI OnActivateEvent(LPVOID p);
void StartQRun(RunQRunInThreadParam* p);
typedef BOOL (WINAPI *_GetFileDesc)(const char*,char sz[256]);
CString GetCurrentDesktopAtom();
void OpenCurrentDeskAtom(BOOL bAdd);

extern CIHotkey DefActionMapHK_Preinit[LAST_ACTION_CODE+1];
extern CIHotkey DefClipMapHK_Preinit[MAX_CLIPS*2+1];
extern CIHotkey DefClipMapHK_H_Preinit[MAX_CLIPS];
extern CIHotkey DefClipMapHK_HA_Preinit[MAX_CLIPS];
extern CIHotkey DefDsSwMapHK_Preinit[MAX_DESKTOPS];
extern CCriticalSection csClipBuffer;
