// This file will be processed by the MIDL tool to
// produce the type library and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(2A7C8C7B-2D94-43EB-8A1A-4FFC1FAEF236),
		helpstring("IWKShellExtender Interface"),
		pointer_default(unique)
	]
	interface IWKShellExtender : IUnknown
	{
	};

[
	uuid(F823821B-152B-475F-BFAC-1AD08AD81C09),
	version(1.0),
	helpstring("WKShellExtender 1.0 Type Library")
]
library WKSHELLEXTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(AC95BA2C-8211-45D4-AB5C-C2A9BCCC8FB6),
		helpstring("WKShellExtender Class")
	]
	coclass WKShellExtender
	{
		[default] interface IWKShellExtender;
	};
};
