#ifndef _COMMON_H_
#define _COMMON_H_
#include "_defines.h"
#include <stdlib.h>
#include <direct.h>
#include <cderr.h>
#include <atlbase.h>
#include <windows.h>
#include <mmsystem.h>
#include <shellapi.h>
#include "..\SmartWires\TI\tiscript.hpp"
#include "..\SmartWires\SmartWndSizer\SmartWndSizer.h"
#include "..\SmartWires\GUIClasses\systemtr.h"
#include "..\SmartWires\GUIClasses\IListCtrl.h"
#include "..\SmartWires\GUIClasses\DLG_Options.h"
#include "..\SmartWires\BitmapUtils\BMPUtil.h"
#include "..\SmartWires\BitmapUtils\CPreviewFileDialog.h"
#include "..\SmartWires\SystemUtils\FileInfo.h"
#include "..\SmartWires\SystemUtils\SystemInfo.h"
#include "..\SmartWires\SystemUtils\SupportClasses.h"
#include "..\SmartWires\SystemUtils\DataXMLSaver.h"
#include "..\SmartWires\SystemUtils\XMLP.h"
#include "..\SmartWires\SystemUtils\AutoUpdate.h"
#include "..\SmartWires\SystemUtils\Zip\ZipArchive.h"
#include "..\SmartWires\SystemUtils\Lik\Stdlik.h"
#include "..\SmartWires\SystemUtils\Lik\checksum.h"
#include "..\SmartWires\SystemUtils\Lik\md5.h"
#include "..\SmartWires\SystemUtils\hotkeys.h"
#include "..\SmartWires\SystemUtils\RemindClasses.h"
#include "..\SmartWires\SystemUtils\WCRenders.h"
#include "..\SmartWires\SystemUtils\RegExp\regexp.h"
#include "WCEnliver\IEnliver.h"
#include "MiscUtils.h"
#include "HtmlWallpaper.h"
#include "WallpaperUtils.h"
#include "WPaper.h"
#include "Settings.h"
#include "DLG_Note.h"
#include "DLG_WChanger.h"
#include "DLG_AddLink.h"
#include "WireChanger.h"
#include "WireChangerDlg.h"
#include "DLG_InfoWindow.h"
//#include "..\SmartWires\BitmapUtils\ximage_wc.h"
#include "..\SmartWires\SystemUtils\Lik\EXECryptor.h"
void AddDebugLog(const char* szFilePref,const char* szText);
CString& AppName();
int& AddDefsInteract();
#endif _COMMON_H_