#ifndef _COMMON_H_
#define _COMMON_H_
#include "_defines.h"
#include <stdlib.h>
#include <direct.h>
#include <cderr.h>
#include <atlbase.h>
#include <windows.h>
#include <mmsystem.h>
#include "resource.h"
#include "..\SmartWires\SmartWndSizer\SmartWndSizer.h"
#include "..\SmartWires\GUIClasses\systemtr.h"
#include "..\SmartWires\GUIClasses\IListCtrl.h"
#include "..\SmartWires\GUIClasses\DLG_Options.h"
#include "..\SmartWires\GUIClasses\FileDialogST.h"
#include "..\SmartWires\GUIClasses\Hyperlink.h"
#include "..\SmartWires\BitmapUtils\BMPUtil.h"
#include "..\SmartWires\BitmapUtils\Videomod.h"
#include "..\SmartWires\BitmapUtils\MenuToolTip.h"
#include "..\SmartWires\SoundUtils\SimpleMixer.h"
#include "..\SmartWires\SystemUtils\FileInfo.h"
#include "..\SmartWires\SystemUtils\SystemInfo.h"
#include "..\SmartWires\SystemUtils\SupportClasses.h"
#include "..\SmartWires\SystemUtils\DataXMLSaver.h"
#include "..\SmartWires\SystemUtils\AutoUpdate.h"
#include "..\SmartWires\SystemUtils\Lik\Stdlik.h"
#include "..\SmartWires\SystemUtils\hotkeys.h"
#include "..\SmartWires\Atl\File\verinfo.h"
#include "..\SmartWires\Atl\crt_cstringw.h"
#include "icondlg.h"
#include "MiscUtils.h"
#include "WKPluginEngine.h"
#include "Settings.h"
#include "WireKeys.h"
#include "WireKeysDlg.h"
#include "DLG_InfoWindow.h"
#include "WKPlugin.h"
#include "Dlg_AppInfo.h"
#endif