<?php 
	global $languageNumber;
	$l=$languageNumber;
?>
<table width="900" border="0" cellspacing="0" cellpadding="0" align="center" >
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top.gif" width=900 height=32></TD>
</TR>
<TR HEIGHT=100 VALIGN=BOTTOM>
	<TD>
	<a href="http://www.wiredplane.com/"><img src="/images2/commons/wiredplane_logo.gif" width=262 height=100></a></TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_products.gif" width=100 height=100>
	<a href="../commons/about.php" style="color: #319aff;"><?php if($l==1){?>Продукты<?php }else{?>Products<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_order.gif" width=100 height=100>
	<a href="../commons/order.php" style="color: #63cf63;"><?php if($l==1){?>Купить<?php }else{?>Order<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_download.gif" width=100 height=100>
	<a href="../commons/download.php" style="color: #ff9a31;"><?php if($l==1){?>Скачать<?php }else{?>Downloads<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_awards.gif" width=100 height=100>
	<a href="../commons/awards.php" style="color: #ff6563;"><?php if($l==1){?>Награды<?php }else{?>Awards<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_contacts.gif" width=100 height=100>
	<a href="../commons/guestbook.php" style="color: #ce65ce;"><?php if($l==1){?>Контакты<?php }else{?>Contacts<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD align=right valign=bottom background="/images2/commons/hmenu_forums.gif" width=100 height=100>
	<a href="http://www.gamerotor.com/forum" style="color: #9c9a9c;"><?php if($l==1){?>Форумы<?php }else{?>Forums<?php }?></a>&nbsp;&nbsp;&nbsp;</TD>
	<TD><img src="/images2/hmenu_space.gif" width=38 height=100></TD>
</TR>
<TR HEIGHT=32>
	<TD COLSPAN=8><img src="/images2/page_top3.gif" width=900 height=32></TD>
</TR>
</TABLE>