#if !defined(AFX_WEBBROWSER2_H__E1C60BCC_D2F5_46A4_B85A_17D0991A0394__INCLUDED_)
#define AFX_WEBBROWSER2_H__E1C60BCC_D2F5_46A4_B85A_17D0991A0394__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2 wrapper class

class CWebBrowser2 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWebBrowser2)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8856f961, 0x340a, 0x11d0, { 0xa9, 0x6b, 0x0, 0xc0, 0x4f, 0xd7, 0x5, 0xa2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

	// Generated message map functions
	virtual void OnNewWindow2(LPDISPATCH* ppDisp, BOOL* bCancel);
	virtual void NavigateError(LPDISPATCH* ppDisp, VARIANT* URL,VARIANT* TargetFrameName, VARIANT* StatusCode, BOOL* bCancel);
	virtual void DocumentComplete(LPDISPATCH pDisp, VARIANT* URL);
	afx_msg void OnPaint();
// Attributes
public:

// Operations
public:
	void GoBack();
	void GoForward();
	void GoHome();
	void GoSearch();
	void Navigate(LPCTSTR URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
	void Refresh();
	void Refresh2(VARIANT* Level);
	void Stop();
	LPDISPATCH GetApplication();
	LPDISPATCH GetParent();
	LPDISPATCH GetContainer();
	LPDISPATCH GetDocument();
	BOOL GetTopLevelContainer();
	CString GetType();
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	CString GetLocationName();
	CString GetLocationURL();
	BOOL GetBusy();
	void Quit();
	void ClientToWindow(long* pcx, long* pcy);
	void PutProperty(LPCTSTR Property_, const VARIANT& vtValue);
	VARIANT GetProperty_(LPCTSTR Property_);
	CString GetName();
	long GetHwnd();
	CString GetFullName();
	CString GetPath();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetStatusBar();
	void SetStatusBar(BOOL bNewValue);
	CString GetStatusText();
	void SetStatusText(LPCTSTR lpszNewValue);
	long GetToolBar();
	void SetToolBar(long nNewValue);
	BOOL GetMenuBar();
	void SetMenuBar(BOOL bNewValue);
	BOOL GetFullScreen();
	void SetFullScreen(BOOL bNewValue);
	void Navigate2(VARIANT* URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
	long QueryStatusWB(long cmdID);
	void ExecWB(long cmdID, long cmdexecopt, VARIANT* pvaIn, VARIANT* pvaOut);
	void ShowBrowserBar(VARIANT* pvaClsid, VARIANT* pvarShow, VARIANT* pvarSize);
	long GetReadyState();
	BOOL GetOffline();
	void SetOffline(BOOL bNewValue);
	BOOL GetSilent();
	void SetSilent(BOOL bNewValue);
	BOOL GetRegisterAsBrowser();
	void SetRegisterAsBrowser(BOOL bNewValue);
	BOOL GetRegisterAsDropTarget();
	void SetRegisterAsDropTarget(BOOL bNewValue);
	BOOL GetTheaterMode();
	void SetTheaterMode(BOOL bNewValue);
	BOOL GetAddressBar();
	void SetAddressBar(BOOL bNewValue);
	BOOL GetResizable();
	void SetResizable(BOOL bNewValue);
	LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam);
	BOOL PreTranslateMessage(MSG* pMsg);
	//DECLARE_EVENTSINK_MAP();
	//DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}

// Microsoft Visual C++ will insert additional declarations immediately before the previous line.
#ifdef _DEBUG
#define FLOG5(x,a,b,c,d,e)	{FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x,a,b,c,d,e);fprintf(f,"\n");fclose(f);};};
#define FLOG4(x,z1,z2,z3,z4){FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x,z1,z2,z3,z4);fprintf(f,"\n");fclose(f);};};
#define FLOG3(x,z1,z2,z3)	{FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x,z1,z2,z3);fprintf(f,"\n");fclose(f);};};
#define FLOG2(x,z1,z2)		{FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x,z1,z2);fprintf(f,"\n");fclose(f);};};
#define FLOG1(x,z1)			{FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x,z1);fprintf(f,"\n");fclose(f);};};
#define FLOG(x)				{FILE* f=fopen("c:\\wk_debug.txt","a+");if(f){fprintf(f,x);fprintf(f,"\n");fclose(f);};};
#define FLOGWND(SS,H);		{char szT[256]={0};char szC[256]={0};::GetWindowText(H,szT,sizeof(szT));::GetClassName(H,szC,sizeof(szC));FLOG3(SS"%08x, '%s', '%s'",H,szT,szC);};
#else
#define FLOG5(x,a,b,c,d,e)
#define FLOG4(x,z1,z2,z3,z4)
#define FLOG3(x,z1,z2,z3)
#define FLOG2(x,z1,z2)
#define FLOG1(x,z1)
#define FLOG(x)
#define FLOGWND(SS,H);		
#endif

#endif // !defined(AFX_WEBBROWSER2_H__E1C60BCC_D2F5_46A4_B85A_17D0991A0394__INCLUDED_)
